---
- name: Update apt cache and upgrade packages
  apt: update_cache=yes upgrade=yes

- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - language-pack-en
    - git
    - python-virtualenv
    - python-pip
    - python-setuptools
    - python-psycopg2
    - python-dev
    - postgis
    - postgresql-9.3
    - postgresql-client-9.3
    - postgresql-contrib-9.3
    - postgresql-9.3-postgis-2.1
    - postgresql-server-dev-9.3
    - libgeos-3.4.2
    - mapserver-bin
    - python-mapnik2
    - libpq-dev