language: python

python:
    - '2.7'

install:
    - "pip install -r requirements/test.txt"

script:
    - py.test -v --cov geopuglia --cov-config .coveragerc

after_success:
    - coveralls -c .coveragerc