---
- name: Create database
  sudo_user: postgres
  postgresql_db: name={{db_name}} encoding=utf8

- name: Create user
  sudo_user: postgres
  postgresql_user: db={{db_name}} name={{db_user}} password={{db_password}} priv=ALL  role_attr_flags=SUPERUSER
