---
- hosts: all
  user: vagrant
  sudo: true
  gather_facts: false
  vars:
    virtualenv_path: /home/vagrant/venv
    virtualenv_binaries: /home/vagrant/venv/bin
    project_folder: /vagrant/geopuglia

  tasks:
    - name: Update apt cache and upgrade packages
      apt: update_cache=yes upgrade=yes

    - name: Install required packages
      apt: name={{ item }} state=present
      with_items:
        - language-pack-en
        - git
        - python-virtualenv
        - python-pip
        - python-setuptools
        - python-psycopg2
        - python-dev
        - postgis
        - postgresql-9.3
        - postgresql-client-9.3
        - postgresql-contrib-9.3
        - postgresql-9.3-postgis-2.1
        - postgresql-server-dev-9.3
        - libgeos-3.4.2
        - mapserver-bin
        - python-mapnik2
        - libpq-dev

    - name: Install required PIP packages inside the virtualenv
      sudo: false
      pip: requirements=/vagrant/requirements/local.txt virtualenv={{ virtualenv_path }}

    - name: Create database geopuglia
      sudo_user: postgres
      postgresql_db: name=geopuglia encoding=utf8

    - name: Run the Postgis SQL scripts
      sudo_user: postgres
      action: command psql -d geopuglia -f {{item}}
      with_items:
        - /usr/share/postgresql/9.3/contrib/postgis-2.1/postgis.sql
        - /usr/share/postgresql/9.3/contrib/postgis-2.1/spatial_ref_sys.sql
        - /usr/share/postgresql/9.3/contrib/postgis-2.1/postgis_comments.sql

#    - name: Grant privileges on spatial tables
#      sudo_user: postgres
#      action: command psql -d geopuglia -c {{item}}
#      with_items:
#        - "GRANT SELECT ON spatial_ref_sys TO PUBLIC;"
#        - "GRANT ALL ON geometry_columns TO geopuglia;"

    - name: Create user geopuglia
      sudo_user: postgres
      postgresql_user: db=geopuglia name=geopuglia password=password priv=ALL